drop table Network Cascade;
drop table TVShow Cascade;
drop table TVShowEpisode Cascade;
drop table Director Cascade;
drop table AssistantDirectorOf Cascade;
drop table MainDirectorOf Cascade;
drop table Consumer Cascade;
drop table Subscription Cascade;
drop table TVShowEpisodeReview Cascade;